#!/bin/bash
#set -x
# Vars
SILENCER='> /dev/null 2>&1'

# -------------------------------------------
# Seafile Server Community Edition on Uberspace
# -------------------------------------------
clear
cat <<EOF
  This script deletes Seafile Server on Uberspace
  -----------------------------------------------------------------
  Make 100% sure you saved the content from your
  libraries before proceeding with the full removal.

  For questions or suggestions please contact me at
  alexander.jackson@seafile.com.de
  -----------------------------------------------------------------
  Hit return to uninstall Seafile or CTRL-C to abort.
EOF
read dummy
clear

# Stop seafile if management script exists
[ -f seafile ] && seafile stop ${SILENCER}

# remove Seafile related directories and files
eval rm -r ~/seafile/ ~/bin/seafile* ~/fcgi-bin/seahub* ${SILENCER}

# Drop databases
for i in haiwen_ccnet haiwen_seafile haiwen_seahub; do
  mysql -e "DROP DATABASE IF EXISTS \`${i}\`;"
done

# Confirm removal
echo Seafile is uninstalled now...
